// Constant to define all master message names
const MASTER_MESSAGES = {
  WORKER_READY: 'WORKER_READY',
  SEND_LOG: 'SEND_LOG',
  ASK_FOR_WORK: 'ASK_FOR_WORK',
  REGISTER_TEST_COUNT: 'REGISTER_TEST_COUNT',
  EXIT_ALL_WORKERS: 'EXIT_ALL_WORKERS'
}

export default MASTER_MESSAGES
